# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: PyTest Hot Reloading

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  test_build_and_publish:
    if: github.repository == 'JamesHutchison/pytest-hot-reloading'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: test
      uses: ./.github/actions/test
    - name: Build distributions
      run: |
        poetry build
    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
